using AutoGenerateXML.Items.Weapons;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static AutoGenerateXML.GunXMLGenerator;
using System.Xml.Linq;
using static AutoGenerateXML.ItemXMLExtensions;

namespace AutoGenerateXML.Items.Accessories
{
    public class ShotgunTubeExtender : ItemXMLGenerator
    {
        public int Capacity = 3;

        public ShotgunTubeExtender() : base()
        {
            OutputPath = Path.Combine("GunMods", "AccessoriesAutoGenerated.xml");
            SelfTags.AddRange(["smallitem", "tool", Tags.VGM_Accessory]);
            Category = "Equipment";

            Name = nameof(ShotgunTubeExtender);
            Identifier = Identifiers.VGM_ShotgunTubeExtender;
        }

        public override string Generate()
        {
            string xmlString =
$@"<Item name=""{Name.FollowedByModPrefix()}"" identifier=""{Identifier}"" category=""{Category}"" subcategory=""{SubCategory}""
    tags=""{ConcatValues(SelfTags)}""
    cargocontaineridentifier=""metalcrate"" scale=""{Scale}"" impactsoundtag=""impact_metal_light"">
    {GenerateAccessoryPreferredContainerXMLsString()}
    <Fabricate suitablefabricators=""VGM_Fabricator"" requiredtime=""35"">
        <RequiredSkill identifier=""weapons"" level=""65"" />
        <RequiredItem identifier=""aluminium"" />
        <RequiredItem identifier=""steel"" amount=""2"" />
    </Fabricate>
    {GenerateItemSpriteXMLString(
        texture: "%ModDir%/EuropaArmedGroupCommunity/VanillaGunModify/GunMods/GunMods.png",
        sourceRect: [256, 416, 48, 9],
        depth: 0.518f,
        origin: [0.5f, 0.5f]
    )}
    {GenerateRectangleBodyXMLString(width: 46, height: 8, density: 15)}
    {GenerateAccessoryThrowableXMLsString()}
    <ItemContainer characterusable=""false"" capacity=""1"" maxstacksize=""{Capacity}"" hideitems=""true"" containedstateindicatorslot=""0"" containedstateindicatorstyle=""bullet"">
        {ChokeTubeMuzzle.GenerateMuzzleSpreadChokeForShotgunTubeExtenderAtSlefContainerXMLsString()}
    </ItemContainer>
</Item>";

            return xmlString;
        }
    }
}