using AutoGenerateXML;

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Reflection.Emit;
using System.Text;
using System.Xml.Linq;

var generatorTypes = Assembly.GetExecutingAssembly().GetTypes()
    .Where(t => t.IsClass && !t.IsAbstract && t.IsSubclassOf(typeof(ItemXMLGenerator)));

var cachedGuns = new Dictionary<string, GunXMLGenerator>();

foreach (var type in generatorTypes)
{
    string? xmlString = null;
    try
    {
        if (Activator.CreateInstance(type) is GunXMLGenerator gunGen)
        {
            cachedGuns.Add(gunGen.Identifier, gunGen);

            xmlString =
$@"<Items>
    {gunGen.Generate()}
</Items>";

            gunGen.VerifyPotentialErrors();

            var xml = XElement.Parse(xmlString);
            xml.AddFirst(new XComment("Auto Generated"));
            string savePath = CleanUpPathCrossPlatform(Path.Combine(UserDefinedGlobal.WorkingDirectory, UserDefinedGlobal.ContentFolder, gunGen.OutputPath));
            string saveFolder = CleanUpPathCrossPlatform(Path.GetDirectoryName(savePath));
            if (!Directory.Exists(saveFolder)) { Directory.CreateDirectory(saveFolder); }
            xml.Save(
                fileName: savePath,
                options: SaveOptions.None
            );

            Console.WriteLine($"Successfully generated and saved XML to {gunGen.OutputPath}");
        }

    }
    catch (Exception ex)
    {
        //if (!string.IsNullOrEmpty(xmlString) && xmlString.Length < 100000)
        //{
        //    Console.WriteLine(xmlString);
        //}
        Console.WriteLine($"Error processing {type.Name}: {ex.Message}");
        return;
    }
}

foreach (var (languageName, languageId) in TextManager.AvailableLanguages)
{
    TextManager.SetLanguage(languageId);

    {
        string savePath = CleanUpPathCrossPlatform(Path.Combine(UserDefinedGlobal.WorkingDirectory, UserDefinedGlobal.ContentFolder, "Languages", languageName, $@"{languageName}GunsAutoGenerated.xml"));
        string saveFolder = CleanUpPathCrossPlatform(Path.GetDirectoryName(savePath));
        if (!Directory.Exists(saveFolder)) { Directory.CreateDirectory(saveFolder); }



        StringBuilder stringBuilder = new StringBuilder();
        var gunList = cachedGuns.ToList();
        gunList.Sort((kv1, kv2) => { return kv1.Key.CompareTo(kv2.Key); });
        gunList.ForEach(kv =>
        {
            string identifier = kv.Key;
            GunXMLGenerator gunGen = kv.Value;

            stringBuilder.AppendLine($@"<entityname.{identifier}>{TextManager.Get($@"entityname.{identifier}")}</entityname.{identifier}>");

            stringBuilder.Append($@"<entitydescription.{identifier}>");

            stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.weapondamage")}:‖end‖ {gunGen.WeaponDamageModifier:0.##%}\n");
            stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.armorpenetration")}:‖end‖ {gunGen.Penetration:0.##%}\n");
            stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.reload")}:‖end‖ {gunGen.Reload}s{(gunGen.ReloadSkillRequirement.HasValue ? $@"~{gunGen.ReloadNoSkill.Value}s" : string.Empty)}\n");
            stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.minimumspread")}:‖end‖ {gunGen.MinimumSpread}°~{gunGen.MinimumUnskilledSpread}°\n");
            stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.spreadchangeswhenaimdownsight")}:‖end‖ {gunGen.SpreadChangesOnAimDownSight:+0.##;-0.##;0}°\n");
            stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.spreadrecoveryrate")}:‖end‖ {gunGen.SpreadRecovery * 60.0f}°/s\n");
            stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.spreadchangeswhenfire")}:‖end‖ {gunGen.SpreadChangesOnShoot:+0.##;-0.##;0}°\n");
            stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.recoil")}:‖end‖ {gunGen.Recoil}\n");
            if (gunGen.CompatibleStocks is not null) { stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.stockrecoilreduction")}‖end‖ ×{gunGen.StockRecoilReductionEfficiency}\n"); }
            stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunstatname.movementspeed")}:‖end‖ {gunGen.StocklessSpeedMultiplier:0.##%}\n");

            stringBuilder.Replace(@"\n", "", stringBuilder.Length - 2, 2);
            stringBuilder.AppendLine($@"</entitydescription.{identifier}>");
        });

        var xmlElementString = XElement.Parse(
$@"<infotexts {TextManager.TextFileRootXMLAttributesString}>
    <!-- Auto Generated -->
    {stringBuilder.ToString()}
</infotexts>");

        using (StreamWriter write = new(savePath, false, Encoding.UTF8))
        {
            write.Write(xmlElementString);
        }
    }

    {
        string savePath = CleanUpPathCrossPlatform(Path.Combine(UserDefinedGlobal.WorkingDirectory, UserDefinedGlobal.ContentFolder, "Languages", languageName, $@"{languageName}GunModsAutoGenerated.xml"));
        string saveFolder = CleanUpPathCrossPlatform(Path.GetDirectoryName(savePath));
        if (!Directory.Exists(saveFolder)) { Directory.CreateDirectory(saveFolder); }

        StringBuilder stringBuilder = new StringBuilder();

        {
            var statList = AccessoryGrip.Stats.ToList();
            statList.Sort((kv1, kv2) => { return kv1.Key.CompareTo(kv2.Key); });
            statList.ForEach(kv =>
            {
                string identifier = kv.Key;
                AccessoryGrip stat = kv.Value;

                stringBuilder.AppendLine($@"<entityname.{identifier}>{TextManager.Get($@"entityname.{identifier}")}</entityname.{identifier}>");

                stringBuilder.Append($@"<entitydescription.{identifier}>");

                if (stat.SpreadChangesOnAimDownSightMultiplier.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.spreadchangeswhenaimdownsightmodifier")}‖end‖ ×{stat.SpreadChangesOnAimDownSightMultiplier.Value}\n");
                }

                if (stat.SpreadRecoveryMultiplier.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.spreadrecoveryratemodifier")}‖end‖ ×{stat.SpreadRecoveryMultiplier.Value}\n");
                }

                stringBuilder.Replace(@"\n", "", stringBuilder.Length - 2, 2);
                stringBuilder.AppendLine($@"</entitydescription.{identifier}>");
            });
        }

        {
            var statList = AccessoryStock.Stats.ToList();
            statList.Sort((kv1, kv2) => { return kv1.Key.CompareTo(kv2.Key); });
            statList.ForEach(kv =>
            {
                string identifier = kv.Key;
                AccessoryStock stat = kv.Value;

                stringBuilder.AppendLine($@"<entityname.{identifier}>{TextManager.Get($@"entityname.{identifier}")}</entityname.{identifier}>");

                stringBuilder.Append($@"<entitydescription.{identifier}>");

                if (stat.RecoilReduction.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.stockrecoilreduction")}‖end‖: {stat.RecoilReduction.Value:0.##}\n");
                }

                if (stat.StocklessBasedSpeedMultiplier.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.movementspeedmodifier")}‖end‖ ×{stat.StocklessBasedSpeedMultiplier.Value}\n");
                }

                stringBuilder.Replace(@"\n", "", stringBuilder.Length - 2, 2);
                stringBuilder.AppendLine($@"</entitydescription.{identifier}>");
            });
        }

        {
            var statList = AccessoryMuzzle.Stats.ToList();
            statList.Sort((kv1, kv2) => { return kv1.Key.CompareTo(kv2.Key); });
            statList.ForEach(kv =>
            {
                string identifier = kv.Key;
                AccessoryMuzzle stat = kv.Value;

                stringBuilder.AppendLine($@"<entityname.{identifier}>{TextManager.Get($@"entityname.{identifier}")}</entityname.{identifier}>");

                stringBuilder.Append($@"<entitydescription.{identifier}>");

                if (stat.WeaponDamageMultiplier.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.weapondamagemodifier")}‖end‖ ×{stat.WeaponDamageMultiplier.Value}\n");
                }

                if (stat.PenetrationModifier.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.armorpenetrationmodifier")}‖end‖ {stat.PenetrationModifier.Value:+0.##%;-0.##%;0%}\n");
                }

                if (stat.SpreadChangesOnShootMultiplier.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.spreadchangeswhenfiremodifier")}‖end‖ ×{stat.SpreadChangesOnShootMultiplier.Value}\n");
                }

                stringBuilder.Replace(@"\n", "", stringBuilder.Length - 2, 2);
                stringBuilder.AppendLine($@"</entitydescription.{identifier}>");
            });
        }

        {
            var statList = AccessoryAimingDevice.Stats.ToList();
            statList.Sort((kv1, kv2) => { return kv1.Key.CompareTo(kv2.Key); });
            statList.ForEach(kv =>
            {
                string identifier = kv.Key;
                AccessoryAimingDevice stat = kv.Value;

                stringBuilder.AppendLine($@"<entityname.{identifier}>{TextManager.Get($@"entityname.{identifier}")}</entityname.{identifier}>");

                stringBuilder.Append($@"<entitydescription.{identifier}>");

                if (stat.SpreadChangesOnAimDownSightMultiplier.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.spreadchangeswhenaimdownsightmodifier")}‖end‖ ×{stat.SpreadChangesOnAimDownSightMultiplier.Value}\n");
                }

                if (stat.SpreadRecoveryMultiplier.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.spreadrecoveryratemodifier")}‖end‖ ×{stat.SpreadRecoveryMultiplier.Value}\n");
                }

                if (stat.MinimumSpreadOnRecoveringMultiplier.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.minimumspreadonrecoveringmodifier")}‖end‖ ×{stat.MinimumSpreadOnRecoveringMultiplier.Value}\n");
                }

                if (stat.ObstructVisionAmount.HasValue)
                {
                    stringBuilder.Append($@"‖color:gui.orange‖{TextManager.Get("gunmodsstatname.obstructvisionamount")}‖end‖: {stat.ObstructVisionAmount.Value:0.##%}\n");
                }

                stringBuilder.Replace(@"\n", "", stringBuilder.Length - 2, 2);
                stringBuilder.AppendLine($@"</entitydescription.{identifier}>");
            });
        }

        var xmlElementString = XElement.Parse(
$@"<infotexts {TextManager.TextFileRootXMLAttributesString}>
    <!-- Auto Generated -->
    {stringBuilder.ToString()}
</infotexts>");

        using (StreamWriter write = new(savePath, false, Encoding.UTF8))
        {
            write.Write(xmlElementString);
        }
    }
}

Console.ReadKey();




static string CleanUpPathCrossPlatform([AllowNull] string path, string directory = "")
{
    if (string.IsNullOrEmpty(path)) { return ""; }

    path = path
        .Replace('\\', '/');
    if (path.StartsWith("file:", StringComparison.OrdinalIgnoreCase))
    {
        path = path.Substring("file:".Length);
    }
    while (path.IndexOf("//") >= 0)
    {
        path = path.Replace("//", "/");
    }

    return path;
}